(* generated by the monitor generator tool rmtld3synth *)
(* This file was automatically generated from rmtld3synth tool version
v0.7 (39aa6b1bfb6a4299a0c7ada2b1b1662773cae41c)
x86_64 GNU/Linux 2025-10-12 17:15. *)
open Rmtld3_eval

module type Trace = sig
  val trc : trace
end

module Rtm_compute_bc0f_0 (T : Trace) = struct
  let env = environment T.trc

  let lg_env = lenv

  let t = 0.

  let mon =
    (fun k s t ->
      b3_not
        ((fun k s t ->
           b3_or
             ((fun k s t ->
                b3_not
                  ((fun k s t ->
                     b3_or
                       ((fun k s t ->
                          b3_not
                            ((fun k s t -> k.evaluate k.trc "a" t) k s t) )
                          k s t )
                       ((eval_uless 10.
                           (fun k s t ->
                             b3_or
                               ((fun k s t -> k.evaluate k.trc "a" t) k s t)
                               ((fun k s t -> k.evaluate k.trc "b" t) k s t) )
                           (fun k s t -> k.evaluate k.trc "c" t) )
                          k s t ) )
                     k s t ) )
                k s t )
             ((fun k s t ->
                b3_not
                  ((fun k s t ->
                     b3_lessthan
                       ((eval_tm_duration
                           (fun k s t -> Dsome 10.)
                           (fun k s t -> k.evaluate k.trc "c" t) )
                          k s t )
                       ((fun k s t -> Dsome 4.) k s t) )
                     k s t ) )
                k s t ) )
           k s t ) )
      env lg_env t
end
(* end *)

let lst = ref []

let myMonitor_set trc = lst := trc

let myMonitor_set_default () =
  lst :=
    [ ("p", 0.)
    ; ("p", 1.)
    ; ("p", 2.)
    ; ("p", 3.)
    ; ("p", 4.)
    ; ("q", 5.)
    ; ("p", 6.)
    ; ("p", 7.)
    ; ("p", 8.)
    ; ("p", 14.) ]

let myMonitor_run () =
  let module T : Trace = struct
    let trc = !lst
  end in
  let module M = Rtm_compute_bc0f_0 (T) in
  if M.mon = Rmtld3_eval.True then print_endline "[true]"
  else if M.mon = Rmtld3_eval.False then print_endline "[false]"
  else print_endline "[unknown]"

open Js_of_ocaml

let array_of_array_of_pairs trc =
  trc |> Js.to_array |> Array.to_list
  |> List.map (fun lst ->
      let p = Js.to_array lst in
      let s = Js.to_string p.(0) in
      (* first element: JS string -> string *)
      let f = p.(1) |> Js.Unsafe.coerce |> Js.float_of_number in
      (* second element: JS number -> float *)
      print_endline (Js.to_string p.(0) ^ "," ^ (f |> string_of_float)) ;
      (s, f) )

let _ =
  print_endline "Ready to run WebAssembly monitor module..." ;
  Js.export "myMonitor"
    (object%js
       method run () = myMonitor_run ()

       method set trc = myMonitor_set (array_of_array_of_pairs trc)

       method setdefault () = myMonitor_set_default ()

       val res = Rmtld3_eval.Unknown
    end )
